import pygame
pygame.mixer.init()
jump = pygame.mixer.Sound("Doodle_Jump/assets/sounds/jump.wav")
shoot_1 = pygame.mixer.Sound("Doodle_Jump/assets/sounds/shoot_1.mp3")
shoot_2 = pygame.mixer.Sound("Doodle_Jump/assets/sounds/shoot_2.mp3")
tile_break = pygame.mixer.Sound("Doodle_Jump/assets/sounds/break.wav")
tile_disappear = pygame.mixer.Sound("Doodle_Jump/assets/sounds/pop.mp3")
button = pygame.mixer.Sound("Doodle_Jump/assets/sounds/button.wav")
monster =  pygame.mixer.Sound("Doodle_Jump/assets/sounds/monster.mp3")
fall =  pygame.mixer.Sound("Doodle_Jump/assets/sounds/fall.mp3")
thump =  pygame.mixer.Sound("Doodle_Jump/assets/sounds/thump.mp3")
die_1 =  pygame.mixer.Sound("Doodle_Jump/assets/sounds/die_1.mp3")
die_2 =  pygame.mixer.Sound("Doodle_Jump/assets/sounds/die_2.mp3")