import pygame
pygame.mixer.init()
jump = pygame.mixer.Sound("Assets/Sounds/jump.wav")
shoot_1 = pygame.mixer.Sound("Assets/Sounds/shoot_1.mp3")
shoot_2 = pygame.mixer.Sound("Assets/Sounds/shoot_2.mp3")
tile_break = pygame.mixer.Sound("Assets/Sounds/break.wav")
tile_disappear = pygame.mixer.Sound("Assets/Sounds/pop.mp3")
button = pygame.mixer.Sound("Assets/Sounds/button.wav")
monster =  pygame.mixer.Sound("Assets/Sounds/monster.mp3")
fall =  pygame.mixer.Sound("Assets/Sounds/fall.mp3")
thump =  pygame.mixer.Sound("Assets/Sounds/thump.mp3")
die_1 =  pygame.mixer.Sound("Assets/Sounds/die_1.mp3")
die_2 =  pygame.mixer.Sound("Assets/Sounds/die_2.mp3")
suck = pygame.mixer.Sound("Assets/Sounds/suck.mp3")
spring = pygame.mixer.Sound("Assets/Sounds/spring.mp3")
trampoline = pygame.mixer.Sound("Assets/Sounds/trampoline.mp3")
jetpack = pygame.mixer.Sound("Assets/Sounds/jetpack.mp3")
propeller = pygame.mixer.Sound("Assets/Sounds/propeller.mp3")
block = pygame.mixer.Sound("Assets/Sounds/block.mp3")
activate_shield = pygame.mixer.Sound("Assets/Sounds/activate_shield.wav")
explosion = pygame.mixer.Sound("Assets/Sounds/explode.wav")

ufo = pygame.mixer.Sound("Assets/Sounds/ufo.wav")
ufo_suck = pygame.mixer.Sound("Assets/Sounds/ufo_suck.mp3")

