import pygame
pygame.mixer.init()
jump = pygame.mixer.Sound("assets/sounds/jump.wav")
shoot_1 = pygame.mixer.Sound("assets/sounds/shoot_1.mp3")
shoot_2 = pygame.mixer.Sound("assets/sounds/shoot_2.mp3")
tile_break = pygame.mixer.Sound("assets/sounds/break.wav")
tile_disappear = pygame.mixer.Sound("assets/sounds/pop.mp3")
button = pygame.mixer.Sound("assets/sounds/button.wav")
monster =  pygame.mixer.Sound("assets/sounds/monster.mp3")
fall =  pygame.mixer.Sound("assets/sounds/fall.mp3")
thump =  pygame.mixer.Sound("assets/sounds/thump.mp3")
die_1 =  pygame.mixer.Sound("assets/sounds/die_1.mp3")
die_2 =  pygame.mixer.Sound("assets/sounds/die_2.mp3")
suck = pygame.mixer.Sound("assets/sounds/suck.mp3")
spring = pygame.mixer.Sound("assets/sounds/spring.mp3")
trampoline = pygame.mixer.Sound("assets/sounds/trampoline.mp3")
jetpack = pygame.mixer.Sound("assets/sounds/jetpack.mp3")
propeller = pygame.mixer.Sound("assets/sounds/propeller.mp3")
block = pygame.mixer.Sound("assets/sounds/block.mp3")
activate_shield = pygame.mixer.Sound("assets/sounds/activate_shield.wav")
